#!/usr/bin/env bash
# File autogenerated by confinit
# These services are automatically enabled in systemd if their monit configuration
# exists in /etc/monit/conf-enabled. Systemd has a condition ConditionPathExists
# checking if monit has the configuration there.

{{ if .Data.monit }}
echo -n "* Enable Monit ... "
rm -f /etc/monit/monit-disabled
{{ else }}
echo -n "* Disable Monit ... "
echo "Disabled by confinit, $(date)" > /etc/monit/monit-disabled
{{ end }}
echo "done"

pushd /etc/monit/conf-enabled >/dev/null

# dnsmasqd
{{ if or .Data.dns .Data.dhcp }}
  echo -n "* Enable dnsmasqd daemon ... "
  ln -sf ../conf-available/dnsmasq
  echo "done"
{{ else }}
  echo -n "* Disable dnsmasq daemon ... "
  rm -f dnsmasq
  echo "done"
{{ end }}

# Opensmtpd
{{ if .Data.smtp }}
  echo -n "* Enable OpenSmtpd daemon ... "
  ln -sf ../conf-available/opensmtpd
  echo "done"
{{ else }}
  echo -n "* Disable OpenSmtpd daemon ... "
  rm -f opensmtpd
  echo "done"
{{ end }}

# Avahi
{{ if .Data.avahi }}
  echo -n "* Enable Avahi daemon ... "
  ln -sf ../conf-available/avahi-daemon
  echo "done"
{{ else }}
  echo -n "* Disable Avahi daemon ... "
  rm -f avahi-daemon
  echo "done"
{{ end }}

# Hostapd (wifi)
{{ if .Data.hostapd }}
  echo -n "* Enable Hostapd daemon ... "
  ln -sf ../conf-available/hostapd
  echo "done"
{{ else }}
  echo -n "* Disable Hostapd daemon ... "
  rm -f hostapd
  echo "done"
{{ end }}

# Bluetooth
{{ if .Data.bluetooth }}
  echo -n "* Enable Bluetooth daemon ... "
  ln -sf ../conf-available/bluetoothd
  echo "done"
{{ else }}
  echo -n "* Disable Bluetooth daemon ... "
  rm -f bluetoothd
  echo "done"
{{ end }}

# SSH
{{ if .Data.sshd }}
  echo -n "* Enable SSH daemon ... "
  ln -sf ../conf-available/openssh-server
  echo "done"
{{ else }}
  echo -n "* Disable SSH daemon ... "
  rm -f openssh-server
  echo "done"
{{ end }}

# Prometheus Node Exporter
{{ if .Data.node_exporter }}
  echo -n "* Enable Prometheus Node Exporter daemon ... "
  ln -sf ../conf-available/node_exporter
  echo "done"
{{ else }}
  echo -n "* Disable Prometheus Node Exporter daemon ... "
  rm -f node_exporter
  echo "done"
{{ end }}

# Docker
{{ if .Data.docker }}
  echo -n "* Enable Docker daemon ... "
  ln -sf ../conf-available/docker
  echo "done"
{{ else }}
  echo -n "* Disable Docker daemon ... "
  rm -f docker
  echo "done"
{{ end }}
popd

exit 0
