logoutput: split
loglevel: debug
datafile: /boot/config/parameters.yml

special_permissions: &permissions
- glob: '*.conf'
  mode: "0644"
- glob: '*.network'
  mode: "0644"
- glob: '*/wpa_supplicant/wpa_supplicant*.conf'
  mode: "0640"
- glob: '*/hostapd/hostapd.conf'
  mode: "0640"
- glob: '*/sudoers.d/*'
  mode: "0640"
- glob: '*/ssh/sshd_config'
  mode: "0644"
- glob: '*/ssh/*key'
  mode: "0600"
- glob: '*/ssh/*key.pub'
  mode: "0644"
- glob: '*.sh'
  mode: "0755"

process:
- source: /boot/config/etc
  operations:
  - destination: /etc
    delete:
      prestart: true
    regex: '.*\.template'
    permissions: *permissions
  - destination: /etc
    template: false
    permissions: *permissions

- source: /boot/config
  operations:
  - destination: /etc/docker-compose
    regex: 'docker-compose\.yml'
    template: false

- source: /boot/config/scripts/boot
  operations:
  - destination: /var/run/confinit/boot
    template: true
    delextension: false
    default:
      mode:
        file: "0755"
    command:
      cmd: ["{{.Destination}}"]

