# Variables defined in .env file
version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    labels:
      description: "Portainer: Web interface to manage docker containers"
      system: true
    volumes:
    - /data/portainer/data:/data
    - /etc/portainer/apps.json:/templates.json
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "9000:9000"
    networks:
    - frontend
    restart: always

networks:
  backend:
  frontend:
    driver: bridge
